// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

import (
	"database/sql"
)

type Todo struct {
	ID        string       `db:"id" json:"id"`
	Title     string       `db:"title" json:"title"`
	Completed bool         `db:"completed" json:"completed"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}
